name: Set delivery rollout - Manual Prd

on:
  workflow_dispatch:
    inputs:
      packageVersion:
        description: "NPM Version of the release (@dcl/third-party-aggregator)"
        required: true
        default: ""

jobs:
  set-manual-rollout-prd:
    runs-on: ubuntu-18.04
    steps:
      - uses: hmarr/debug-action@v2
      - name: Set Rollout Prd
        uses: decentraland/set-rollout-action@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

          # Repo deployment info
          ref: ${{ github.event.ref }}
          sha: ${{ github.sha }}

          # CDN information
          packageName: "@dcl/third-party-aggregator"
          packageVersion: ${{ github.event.inputs.packageVersion }}

          # Rollout information
          deploymentDomain: third-party-aggregator.decentraland.org
          deploymentName: "_site"
          percentage: 100
